allowBuilds:
  '@carbon/icon-helpers': set this to true or false
  '@carbon/icons-react': set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
